# This is the SAM template that represents the architecture of your serverless application
# https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-template-basics.html

# The AWSTemplateFormatVersion identifies the capabilities of the template
# https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/format-version-structure.html
AWSTemplateFormatVersion: '2010-09-09'
Description: >-
  lambda-contacts

# Transform section specifies one or more macros that AWS CloudFormation uses to process your template
# https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/transform-section-structure.html
Transform:
- AWS::Serverless-2016-10-31

# Resources declares the AWS resources that you want to include in the stack
# https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/resources-section-structure.html
Resources:
  # Each Lambda function is defined by properties:
  # https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction

  ExpressApi:
    Type: AWS::Serverless:Api
    Properties:
      StageName: prod
      BinaryMediaTypes: ['*/*']

  getNewRefreshToken:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/api/server.handler
      Runtime: nodejs14.x
      MemorySize: 128
      Timeout: 100
      Description: Interface to authorize the API for the first time.
      Environment:
        Variables:
          AWS_PROFILE:
          AWS_REGION:
          AWS_SECRET_ID:
          CC_API_KEY:
          CC_API_SECRET:
          CC_API_SCOPE:
      Events:
        ProxyApiRoot:
          Type: Api
          Properties:
            RestApiId: !Ref ExpressApi
            Path: /
            Method: ANY
        ProxyApiGreedy:
          Type: Api
          Properties:
            RestApiId: !Ref ExpressApi
            Path: /{proxy+}
            Method: ANY

  getUserPrivileges:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/get-user-privileges.handler
      Runtime: nodejs14.x
      MemorySize: 128
      Timeout: 100
      Description: Get user privileges from Constant Contact.
      Environment:
        Variables:
          AWS_PROFILE:
          AWS_REGION:
          AWS_SECRET_ID:
          CC_API_KEY:
          CC_API_SECRET:
          CC_API_SCOPE:

Outputs:
  WebEndpoint:
    Description: "API Gateway endpoint URL for Prod stage"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
